---
name: test

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
